[package]
name = "cairo-vm-pipeline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-lang-runner = "2.5.3"
cairo-vm = "0.9.2"
